<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-AV552BS" failures="1" tests="1" name="Surefire test" time="2.718" errors="0" timestamp="2025-09-18T00:56:52 ICT">
  <testcase classname="tests.LoginTests" name="lockedUserLogin" time="1.075">
    <failure type="java.lang.AssertionError" message="
Expected error message to contain: &amp;apos;Epic sadface:11 Sorry, this user has been locked out.&amp;apos;
Current error message is: &amp;apos;Epic sadface: Sorry, this user has been locked out.&amp;apos;.
 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 
Expected error message to contain: 'Epic sadface:11 Sorry, this user has been locked out.'
Current error message is: 'Epic sadface: Sorry, this user has been locked out.'.
 expected [true] but found [false]
at tests.BaseTest.assertFinalResult(BaseTest.java:28)
at tests.LoginTests.lockedUserLogin(LoginTests.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- lockedUserLogin -->
  <testcase classname="tests.LoginTests" name="validLogin" time="0.0">
    <ignored/>
  </testcase> <!-- validLogin -->
</testsuite> <!-- Surefire test -->
